let initialState = localStorage.getItem('userSettings') !== null ? JSON.parse(localStorage.getItem('userSettings')) : {
  sessionTotal: 1500,
  direction: 'backward',
  breakTotal: 300,
  pomodoros: 4,
  isOn: false,
  isReset: false,
  isSet: false,
  totalTimeEver: 0,
  totalTimeToday: 0,
  isTicking: true,
  clockTickSound: '1',
  hasThreeMinWarning: true,
  plantChoice: 'Tomato',
  growthRate: 1,
  plantMaxImgNum: 5,
  selectHighContrast: '',
  errorPresent: false,
  haveServerMessage: false,
  serverResponseMessage: null,
  willLogin: true,
  willCreateLogin: false,
  user: '',
  password: '',
  loggedIn: false,
  saveToDatabase: false,
  willLogTime: false,
}
console.log('local storage:', JSON.parse(localStorage.getItem('userSettings')), 'initialState:', initialState)
export default initialState;