let initialState = {
  sessionTotal: 1500,
  direction: 'backward',
  breakTotal: 300,
  pomodoros: 4,
  isOn: false,
  isReset: false,
  isSet: false,
  totalTimeEver: 60,
  totalTime: 20,
  isTicking: true,
  clockTickSound: '1',
  hasThreeMinWarning: true,
  plantChoice: 'Tomato',
  growthRate: 1,
  plantMaxImgNum: 5,
  selectHighContrast: '',
  errorPresent: false,
  haveServerMessage: false,
  serverResponseMessage: undefined,
  willLogin: true,
  willCreateLogin: false,
  user: '',
  password: '',
  loggedIn: false,
  saveToDatabase: false,
  willLogTime: false,
  willSaveSettings: false,
}

export default initialState;